### ISSUE TITLE
SRRS Validation

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/hdash_air#2]
A couple of notes from review of SRRS hdash validation errors:

- SRRS will not have a Demographics file. Can we exclude the center from this check? 

- There are currently many parent link errors, for example: `HTA15_30007_1400001 references parent ID=HTA15_30007, but no such ID exists. [Error occurred while processing file: syn51607146 of type SRRSBiospecimen].`  However, HTAN Participant ID `HTA15_30007` does exist in the SRRSClinicalDataTier2 manifest: https://www.synapse.org/#!Synapse:syn51607133. @ecerami, would you be able to look into this?

**Comment by ecerami** [comment]
@clarisse-lau I did the first part.  SRRS now passes the demographics test. See:  http://hdash.website-us-east-1.linodeobjects.com/HTA15.html.

The second part is more complicated, thinking on that one next.

**Comment by ecerami** [comment]
@clarisse-lau ok, I tired a fix for the second part, and I got the number of linking errors to go down from 338.  But, I still see 209 linking errors.  See:  http://hdash.website-us-east-1.linodeobjects.com/HTA15.html.  Do these look accurate?  or is there somewhere else in SRRS I need to look?

**Comment by ecerami** [comment]
@clarisse-lau Actually I think these new validation errors are correct.

There are currently only 8 records specified in SRRSClinicalDataTier2.

And, this error:  "HTA3_11009_15000001 references parent ID=HTA3_11009, but no such ID exist" appears to be correct.

So... I am going to close this issue and consider it fixed.  If you find otherwise, just reopen.  thanks.
